codename = input('Please enter your Codename:')
realname = input('Please enter your Real Name:')
gadget = input('Enter assigned gadget:')
location = input('Please enter the Mission location:')
number = input('Please enter you operation number:') 
print('****************************************')
print('      TOP SECRET - AGENT DOSSIER')
print('****************************************')
print('\nCodename:   ' + '[' + codename + ']')
print('Real Name:  ' + '[' + realname + ']')
print('Gadget:     ' + '[' + gadget + ']')
print('\n----------------------------------------')
print('MISSION DETAILS:')
print('Operation ID:   OP-' + '[' + number + ']-[' + codename + ']')
print('Location:       [' + location + ']')
print('----------------------------------------')
print('       *** FOR YOUR EYES ONLY ***')
print('****************************************')